- src/ImapMailbox.php
I've added a check for the mbstring extension but please take a look at the rest of the changes. Suppressing the ```iconv``` notice may not be desirable but I can't think of any other way around the error at the moment, other than skipping it and returning the untouched string when that happens.
> Updated Fix for #46

- src/PhpImap/Mailbox.php
imap_qprint seems to have problems with strings containing the character set (like described here: http://php.net/manual/de/function.imap-qprint.php#4009) - quoted_printable_decode works much better
> fixed decoding of subject

- composer.json
Since imap extension is required, it's recommeded that composer knows about it!
Upon installation on system with no imap extension installed/activated, composer will alert user!
> Update composer.json with imap requirement

- src/PhpImap/Mailbox.php
Adding copy functionality, in same manner as move functionaltiy. Tested and works. Unsure if `&& $this->expungeDeletedMails()` is absolutely needed for copy. Also added comment for moveMail().
> Copy Mail function

- src/PhpImap/Mailbox.php
Sometimes you want to use another mail parser and you need raw message.
```php
$rawMail = $mailbox->getRawMail($mailId);
```
> Add method to fetch raw email message

- src/PhpImap/Mailbox.php
Function imap_utf7_decode works incorrect in some cases (for example - cyrillic in gmail folders)
> Fix broken folders name in some cases

- src/PhpImap/IncomingMail.php
- src/PhpImap/Mailbox.php
According to https://github.com/barbushin/php-imap/issues/102 added header data, and raw data of them to IncomingMail.
Signed-off-by: Rainer Bendig <hexathos@gmail.com>
> Added Header Data

- src/PhpImap/Mailbox.php
see also https://github.com/barbushin/php-imap/issues/71
> ignore contentId on body when mail isn't multipart

- src/PhpImap/Mailbox.php
Currently it's not possible to search multiple folders without re-connecting to the server.
This PR can solve this issue
Just added this simple function to ```Mailbox.php```
```php
public function switchMailbox($imapPath = '') {
$this->imapPath = $imapPath;
$imapStream = @imap_reopen($this->getImapStream(), $imapPath);
if(!$imapStream) {
throw new Exception("Couldn't switch  mailbox: " . imap_last_error());
}
}
```
Now you can do this:
```php
// Connect to INBOX on server and search for mails
$mailbox = new PhpImap\Mailbox('{imap.example.org.com:993/imap/ssl}INBOX', 'john.doe@example.org', '*********', __DIR__);
$mailIds = $mailbox->searchMailbox('ALL');
// store all mails in $inbox
$inbox = [];
foreach($mailIds as $mailId)
{
$inbox[] = $mailbox->getMail($mailId, false);
}
// Switch to …
```
> Add functionality to switch mailbox(es) without opening a new connection

- src/PhpImap/Mailbox.php
Clear imap errors. If do not clear then imap errors are shown at the end of php script execution even if we tried to catch all exceptions.
> Clear Imap Errors

- src/PhpImap/Mailbox.php
Without call `setImapPath` non English-name folders can't be retrieved.
> Fix for switchMailbox

- src/PhpImap/Mailbox.php
imap_delete() seems to want a range, so to select one, simply range from your id to your id.
> fix deleteMail function does not work

- src/PhpImap/Mailbox.php
The current version of PHP-Imap does not check if a part is an attachment, and thus will parse an RFC822 compliant file. I don't believe this to be the intended behavior.
> Prevent Parsing of attachments

- src/PhpImap/Mailbox.php
Hi,
On mailboxes that are not below `INBOX` the `shortpath` property from `getMailboxes` is incorrect (depending on the lenght of the `fullpath` it will contain parts of `fullpath` or be shorter).
This PR only extracts the part after the `}` of the `fullpath`, thus givin a correct folder name.
Only warning is that this change might break something for users using it and whose IMAP folders are always below `INBOX`
> Fix incorrect shortpath on mailboxes outside INBOX

- .gitignore
- composer.json
- composer.lock
- phpunit.xml
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- tests/unit/RequirementsTest.php
I've added some basic PHPUnit tests:
```
$ phpunit --testdox
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.26-2+0~20190216175340.13+stretch~1.gbpc20626
Configuration: /home/sebastian/git/php-imap/phpunit.xml
Mailbox
✔ Constructor [4.15 ms]
✔ Constructor trims possible variables [0.34 ms]
✔ Constructor uppers server encoding [0.06 ms]
✔ Set and get server encoding [0.05 ms]
✔ Get login [0.04 ms]
Requirements
✔ Php imap extension is enabled [0.17 ms]
Time: 43 ms, Memory: 4.00 MB
OK (6 tests, 10 assertions)
```
Due to these tests, I've added `trim()` to some variables in the constructor.
> Added some basic PHPUnit tests

- src/PhpImap/Mailbox.php
PR #281 is currently only converting the `$args`, when one of these methods is called:
- open
- reopen
- search
Expected behaviour:
The `$args` should be converted always, except when the method `open` is called. The `open` method is the only imap function, which uses credentials (username + password). The encoding might change these values that they become different to the original provided values.
I've already created a PR in @nickl- repository for this change, but he needs to merge this and update his PR here.
Feel free to close and merge whichever PR you want to. :)
> Don't convert $args for imap_open

- src/PhpImap/Mailbox.php
Split PR of #239 all original commits by @commanddotcom only cherry picked, branched, squashed.
This fixes #242 username and password encoding might render the credentials unusable.
> SPLIT #239:::Don't convert $args for imap_open

- src/PhpImap/Mailbox.php
Added support for getting the following headers:
- **Priority**: Can be "normal", "urgent" or "non-urgent" and can influence transmission speed and delivery. (RFC 1327, not for general usage)
- **Importance**: A hint from the originator to the recipients about how important a message is. Values: High, normal or low. Not used to control transmission speed. (RFC 1327 and RFC 1911, experimental)
- **Sensitivity**: How sensitive it is to disclose this message to other people than the specified recipients. Values: Personal, private, company confidential. The absence of this header in messages gatewayed from X.400 indicates that the message is not sensitive. (RFC 1327 and RFC 1911, experimental)
> Extended getMailHeader()

- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- Added functions to set/get path delimiter
- Added default value `.` for property `path delimiter` as this was used before in the code
- Added PHPUnit tests for path delimiter
This solves #213.
```
$ phpunit --testdox
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.26-2+0~20190216175340.13+stretch~1.gbpc20626
Configuration: /home/sebastian/git/php-imap/phpunit.xml
Mailbox
✔ Constructor [3.78 ms]
✔ Constructor trims possible variables [0.33 ms]
✔ Constructor uppers server encoding [0.06 ms]
✔ Set and get server encoding [0.05 ms]
✔ Get login [0.04 ms]
✔ Path delimiter has a default [0.34 ms]
✔ Path delimiter is being checked [0.31 ms]
✔ Set and get path delimiter [0.05 ms]
Requirements
✔ Php imap extension is enabled [0.05 ms]
Time: 44 ms, Memory: 4.00 MB
OK …
```
> Made path delimiter configurable / dynamic and improved de-/encoding of strings

- README.md
- composer.json
phpunit is not required in production, only for development.
Fixes #302
> Move phpunit to require-dev

- composer.json
PHPUnit should be in the require dev, not require.
This change broke my project, which requires phpunit 6+.
> move phpunit to require dev

- src/PhpImap/Mailbox.php
Split PR of #239 all original commits by @commanddotcom only cherry picked, branched, squashed.
This PR fixes #39 #71 #229 body content gets incorrectly processed as attachments.
plain text and html can have id as well so email part can't be marked as attachment based on id
> SPLIT #239:::Content as attachments

- README.md
- src/PhpImap/Mailbox.php
Split PR of #239 all original commits by @commanddotcom only cherry picked, branched, squashed.
This fixes #150 #167 #122 provides a way to skip processing of attachments when it is not required.
> SPLIT #239:::Skip attachments

- src/PhpImap/DataPartInfo.php
- src/PhpImap/IncomingMail.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
Something along these lines...
fixes #150 #167 #122  as discussed at #284 
instead of trying to avoid loading attachments rather put it off until it is needed.
we can do the same for text plain and text html as well, what you don't need won't be retrieved.
solution remains non breaking, public lazy load properties are implemented as property magic getter
nJoy!
> Lazy load message text and attachments data

- src/PhpImap/DataPartInfo.php
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- Updated comments, made code a bit more dynamic, used setAttachmentsDir() in constructor
- Added condition for setting attachments dir in constructor
- Issue #232: Added test strings with emojis (smiles) to PHPUnit test
- Issue #232: Added strings to test decodeMimeStr() in PHPUnit test with non-UTF8 server encoding
- Issue #232: Fixed broken UTF-8 decoded strings, when not using UTF-8 as server encoding
- Issue #265: Added string to test iconv() in PHPUnit test
- Issue #274: Some strings with default charset had UTF-8 characters and failed to convert
> Mainly fixed decoding issues

- src/PhpImap/Mailbox.php
array_key_exists() -> in_array()
>  Fix an issue that checking valid params in the setConnectionArgs function.

- .codeclimate.yml
- src/PhpImap/DataPartInfo.php
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- Fix an issue that checking valid params in the setConnectionArgs function
- Issue #324: Changed string encoding from decodeMimeStr() to convertStringEncoding()
- Removed first check, if param is array as it would never throw an exception otherwise
- Added info to setConnectionArgs(), which option is invalid
- PR #325: PHPUnit tests were not working as expected
> Fixed PHPUnit tests, setConnectionArgs() and string encoding

- src/PhpImap/Mailbox.php
Resolve an issue #335 introduced with e4d5130b7d539bc636c397c68f7c94cb62ef8e3b
The mentioned commit caused convertStringEncoding method to skip conversion if the source encoding was one of the windows encodings. This changes make the method fallback to iconv if the source or final encoding are not found in the list of encodings returned by mb_list_encodings().
> Windows charset conversions

- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
Although, it is not the ideal solution for this problem, but I've been able to make it works with eml files,
Using the actual branch (develop), I've been able to:
- Download de the eml file as ".eml" attached file
- Download each file "inside" fhe eml as a different attachment
- "Mark" (as a parameter called "emlOrigin") if the attachment comes from an eml files
Example, of processed EML "attachment":
- 10431_5845944131528768489_5845944131528768489.rfc822.eml
- 10431_9025868031894177481_9025868031894177481.plain
@Sebi94nbg , what do you think? Any problems than colud arise with this solution?
To do this, the code to download the attchment has been split into another function (downloadAttachment). If it is ok, could someone help me with the comments? English is not my primary language.
> Fix for parsing parts do not work properly

- src/PhpImap/Mailbox.php
Subject must be checked is not empty.
> Fixes "decodeMimeStr() Can not decode an empty" error when mail has no subject.

- src/PhpImap/Mailbox.php
Handle at least Gmail multipart/related way of structuring mail with attachments
> Flatten mail parts before parsing

- src/PhpImap/Mailbox.php
Sometimes I receive emails with the next raw header:
```
........
Date: Wed, 26 Jun 2019 07:49:33 +0100
Subject: 20% OFF GARDEN FURNITURE!!
From: TJ Hughes <no-reply@tjhughes.co.uk>
To: " " <myemail@gmail.com>
Content-Type: multipart/alternative;
.........
```
You can clearly see a space in "To" field. So instead of simply skipping this field I got an Exception and can not fetch email at all. I suggest that trim is using before decoding in this case.
> trim $to->personal field before decoding

- src/PhpImap/Mailbox.php
There is an issue with google mail messages composed via web-mail. Message composer supports clipboard image paste direct into the body. When I received the email, I didn't see all the attachments, because google web-mail assigns the same image name for any pasted images.
The issue is solved when we generate attachment.id based on content.id.
> ContentId based attachment key calculation

- README.md
- src/PhpImap/Mailbox.php
For some cases if characters set is not detected correctly iconv will remove characters from content and that makes it hard to read. 
For example if original text is 
> Geri vyrai gerą girą gėrė
It's possible to get the result that looks like this:
> Geri vyrai ger gir gr
With transliteration enabled it's easier to read text when such problem happens. The result would look like this:
> Geri vyrai gera gira gere
This one line change adds such functionality.
> iconv in convertStringEncoding trieds to TRANSLIT first before ignore illegal encoding characters

- src/PhpImap/Mailbox.php
FIX incorrectly implemented #360 (switchMailbox) and result bug in #372 
Works with
```
* {mail.example.com:143/imap/tls/validate-cert}INBOX
* {mail.example.com:143/imap/tls/validate-cert}
````
Tested with short path folder:
````
//{mail.example.com:143/imap/tls/validate-cert}test
$mailbox->switchMailbox("test");
$idss = $mailbox->searchMailbox('ALL',true);
var_dump($idss);
````
new feature to switch back to root folder. It is BC. Also fullpath test
````
$mailbox->switchMailbox("/");
$folders = $mailbox->getMailboxes('*');
foreach($folders as $folder) {
$mailbox->switchMailbox($folder['fullpath']);
$ids = $mailbox->searchMailbox('ALL',true);
var_dump($ids);
}
````
> Bugfix update getCombinedPath and switchMailbox

- README.md
- src/PhpImap/Mailbox.php
* Adds @see tags for wrappers around imap_* functions
* Makes it clearer when $mailId is a message number (integer) or a range (string)
* Adds string type to $mailBox in move() and copy() to make it clear the method doesn't expect a Mailbox instance but a string
> Improve phpDoc

- src/PhpImap/IncomingMail.php
- src/PhpImap/IncomingMailAttachment.php
This PR:
1) Allows for an attachment to be retrieved as a string without being saved as a file
2) Provides a method to retrieve the mime type of an attachment
3) Allows for IncomingEmail to remove an attachment by id
4) Adds a method to IncomingEmail that can embed inline image attachments as base64 encoded data to the <img> tag
> Various attachment related imporevements

- examples/get_and_parse_unseen_emails_save_attachments_one_by_one.php
- src/PhpImap/DataPartInfo.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
- Issue #390: Fixed, that attached HTML files got merged into the `textHtml` property
- Issue #397: `convertStringEncoding()` will now always return a string and never throw an exception
- Issue #398: Fixed issue, that files could not be manually (one by one) saved to disk using `saveToDisk()`
- Issue #400: Fixed issue, that `empty()` returned a wrong result for strings with only whitespaces
- Updated some PhpDoc comment-blocks
- Improved code of `DataPartInfo` to be more human-readable
- Removed wrong `if`-condition in `DataPartInfo::fetch()`
- Fixed a few PhpCS warnings (eg. `Expected type X, but Y given`)
- Resorted $attachment property assignments based on IncomingMailAttachment properties order
> Bug fixes and improvements

- .travis.yml
should ensure travis runs a stable version of php 7.4
> snaphsot no longer needed

- .editorconfig
inadvertently created a tab-indented file when creating #419
> adding a .editorconfig file to avoid tab indents

- composer.json
- examples/get_and_parse_all_emails_with_matching_subject.php
- examples/get_and_parse_all_emails_without_saving_attachments.php
- examples/get_and_parse_unseen_emails.php
- examples/get_and_parse_unseen_emails_save_attachments_one_by_one.php
- psalm.baseline.xml
- psalm.xml
- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
this PR includes #433 
In order to explain the proliferation of `mixed` and `scalar|array|object|resource|null`, I'm currently trying to avoid having code *rely* on psalm being in use (which would necessitate adding a conflict entry in composer.json).
example:
```php
function foo($s) {
if (is_int($s)) {
echo 'foo';
}
}
```
If the preceding example were to have `@param int $s` in it's docblock, this would result in a [`RedundantConditionGivenDocblockType` issue being flagged](https://psalm.dev/r/71b8f0113c). While one *could* then add such an error to the baseline file, I find it preferable to remove entries over time rather than adding to them.
> further static analysis with psalm

- .travis.yml
the default diff mode is [a little unwieldly](https://travis-ci.org/bapcltd-marv/php-imap/jobs/640816500), `--diff-format=udiff` doesn't print out the entire file with the changes.
p.s. travis build failure is fixed in #441
> request for setting diff mode to use the udiff format

- .php_cs.dist
- src/PhpImap/IncomingMail.php
- src/PhpImap/Mailbox.php
for purposes of expediency, I'm needing to add downstream features on the forked master branch, then pull them back into a develop-based branch.
this rule seems to placate some of the more confusing git diffs by applying a consistent order to the methods (it's a config option set in the preferred php-cs-fixer config used in the downstream fork).
> enabling ordered class elements php-cs-fixer rule

- psalm.baseline.xml
- src/PhpImap/DataPartInfo.php
- src/PhpImap/Imap.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
- tests/unit/LiveMailboxTest.php
- tests/unit/MailboxTest.php
kept on stumbling into type errors re: #432, so I've backported a strongly-typed implementation from my fork that only supports php 7.4.
github had a little snafu- I was trying to leave this as a draft while I tinkered with the implementation further.
> separate imap class for handling imap_* functions

- .travis.yml
- composer.json
* uses env to as control rather than php version
* unloads xdebug when not running coverage
* only fetches cc-test-reporter when running coverage
* drops phpcov merging in favour of only running coverage on php 7.4
> rewrite how travis tasks are run

- .travis.yml
- psalm.baseline.xml
- src/PhpImap/Imap.php
as mentioned in #460, waiting for travis to run the `@group live` tests is tedious.
since #460 also shifted coverage generation solely onto php 7.4, it speeds things up a little to exclude the `@group live` tests from everywhere *except* php 7.4.
as `paragonie/hidden-string` is only (currently) required for the live tests, builds can be sped up a non-zero amount by not installing it.
> waiting for builds to finish is tedious

- .editorconfig
- composer.json
added because manually copying & pasting lines from the travis config was becoming tedious.
> adding script to run tests locally

- src/PhpImap/Imap.php
making arguments conditional ensures valid sequences are processed
appropriately.
`Mailbox::setFlag([1,2,3], '\\Seen');` got boiled down to `Imap::setflag_full($this->imapStream, '1,2,3', '\\Seen', ST_UID);`, conditional failing to fail was incorrectly expecting a range, rather than succeeding.
> matching sequence fell back to range match

- .gitignore
- .travis.yml
- psalm.xml
psalm runs faster if it's cache is persisted between runs & is therefore allowed to utilise the diff flags.
> Cache psalm

- .travis.yml
- src/PhpImap/Imap.php
- tests/unit/AbstractLiveMailboxTest.php
- tests/unit/LiveMailboxTest.php
- tests/unit/LiveMailboxWithManualSetupTest.php
- tests/unit/MailboxTest.php
* bd7dfce [fails](https://travis-ci.org/github/bapcltd/php-imap/builds/685333307) as reported in #499 
* ef4a5ab [passes](https://travis-ci.org/github/bapcltd/php-imap/builds/685335052) with the patch suggested by jeanphiB
note this PR introduces a live mailbox test that requires manual setup- in this case, a `Éléments envoyés` folder inside a  `issue-499` folder.
> fixes #499

- .travis.yml
- src/PhpImap/Mailbox.php
- tests/unit/AbstractLiveMailboxTest.php
- tests/unit/LiveMailboxIssue501Test.php
- tests/unit/LiveMailboxTest.php
- tests/unit/LiveMailboxWithManualSetupTest.php
- tests/unit/MailboxTest.php
* fixes #501
* uses multiple groups on test methods rather than multiple entries on travis `phpunitflags`
> fixes #501

- composer.json
- src/PhpImap/Mailbox.php
- tests/unit/LiveMailboxIssue490Test.php
* ~`a852f76 and ed8a361 are cherry-picked from #502`~ rebased
* ~1f7ca2b~ bd79ccf makes running static analysis a separate command, which is handy when developing live mailbox tests for just one issue.
* ~4070523~ f54808e implements tests which [replicate the issue, failing as expected](https://travis-ci.org/github/bapcltd/php-imap/builds/687073606)
* ~d5bea081~ 2ff6116 implements the fix which [~should succeed~ succeeds on travis as it does locally](https://travis-ci.org/github/bapcltd/php-imap/builds/687477715)
> avoid adding plain text attachments to `IncomingMail::$dataInfo`

- psalm.baseline.xml
- src/PhpImap/IncomingMail.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
hadn't noticed these until I was rebasing for our drop/php-7.3 branch.
this pr fixes the travis build failures caused by recent commits.
currently feeling unsure about the `psalm-type` introduced in 332aebf, thoughts?
> fixing travis build

- README.md
- src/PhpImap/Mailbox.php
- tests/unit/Fixtures/Mailbox.php
- tests/unit/MailboxTest.php
fix for #510 
* d33cde8 23500a0 facilitate having the non-exception tests perform assertions again (used to be null return, now void return, fixture class gives it something useful to check).
* 252ac48 removes duplicate test cases & switches to generator to allow tests to be dynamically compiled without dumping the array all at once.
* 76aca70 generator keys were prepended on previous lines to separate the diff from the commit that satisfies php-cs-fixer
* 96c241e dynamically compiles a bunch of mostly-exhaustive combinations for testing (don't think it's entirely exhaustive but close enough)
* 7077fcc allow bitmask options, as per [discussion on issue](https://github.com/barbushin/php-imap/issues/510#issuecomment-633208704)
* e08ea90 add example of bitmask usage [as per …
> implementing bitmask validation of imap options, fixes #510

- src/PhpImap/Imap.php
- tests/unit/AbstractLiveMailboxTest.php
- tests/unit/LiveMailboxIssue250Test.php
- tests/unit/LiveMailboxTest.php
* this changeset adds a test for #250 
* this changeset "fixes" #250 by disabling utf7 imap encoding by default
* this changeset does not presently feature a way to enable encoding via `Mailbox` search methods, it's only available on `Imap::search()`
this fixes a bug by changing the default behaviour of the `Mailbox` & `Imap` classes- definitely something to mention in the changelog if accepted, but also wondering what the implications of the change are.
[the manual](https://www.php.net/manual/en/function.imap-utf7-encode.php) suggests utf7 imap encoding is only needed for *mailboxes*, so 🤷‍♂️?
draft pending #504
> Disable utf7 imap encoding of search criteria by default

- tests/unit/Issue509Test.php
oversight in original PR, renamed test/file.
> rename barbushin/php-imap#509 test to follow pattern of other tests

- composer.json
- psalm.baseline.xml
"Match" becoming a reserved word currently makes travis fail.
~psalm baseline~ version constraint needs to be revisted pending outcome of nikic/PHP-Parser#690
> Unexpected T_MATCH

- src/PhpImap/DataPartInfo.php
- src/PhpImap/Mailbox.php
The decodeMimeStr now uses the encoding from DataPartInfo.php if it was set
> Fix for #525 How to detect textPlain encoding

- src/PhpImap/IncomingMailAttachment.php
As the __get() method could also return null or false for the filePath property, these types should be added to the @property annotation.
> Add false and null to possible (magic) property filePath property type in IncomingMailAttachment

- src/PhpImap/IncomingMail.php
- src/PhpImap/Mailbox.php
See https://github.com/barbushin/php-imap/issues/569.
> 569: Fix broken inline images when header does not contain "Content-Disposition: inline"

- README.md
Hold on!
Does this method really exist?? Cause `$mailbox->imap('mailboxmsginfo');` is giving me:
> Attempted to call an undefined method named "imap" of class "PhpImap\Mailbox".
> Adding link to PHP docs

- src/PhpImap/IncomingMail.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
In **src/PhpImap/IncomingMailAttachment.php**
```php
if ((FILEINFO_MIME == $fileinfo_const) && (false != $this->mimeType)) {
return $this->mimeType;
}
```
$this->mimeType - currently never set, condition always false. Deleted as unnecessary.
Added default field definition in **src/PhpImap/Mailbox.php**
```php 
$attachment->mimeType = $attachment->getFileInfo(FILEINFO_MIME_TYPE);
```
Also i found incorrect use of mime type in **src/PhpImap/IncomingMail.php -> embedImageAttachments()**
```php
$contentType = (string) $attachment->getFileInfo(FILEINFO_MIME);
$base64encoded = \base64_encode($contents);
$replacement = 'data:'.$contentType.';base64, '.$base64encoded;
```
For example for jpeg image **FILEINFO_MIME** is **image/jpeg; charset=binary**, and for correct base64 need only mime type …
> Add FILEINFO_MIME_TYPE support (fix incorrect bugfix)

- README.md
- src/PhpImap/Mailbox.php
Either directly in the constructor:
```php
// Create PhpImap\Mailbox instance for all further actions
$mailbox = new PhpImap\Mailbox(
'{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
'some@gmail.com', // Username for the before configured mailbox
'*********', // Password for the before configured username
__DIR__, // Directory, where attachments will be saved (optional)
'UTF-8', // Server encoding (optional)
true, // Trim leading/ending whitespaces of IMAP path (optional)
true // Attachment filename mode (optional; false = random filename; true = original filename)
);
```
Or any time later in the code:
```php
// set attachment filename mode to "original filename"
$mailbox->setAttachmentFilenameMode(true);
```
You also can get the current configuration:
```php
// get …
```
> Add support for original filename for attachments

- src/PhpImap/Imap.php
```
Fatal error: Uncaught TypeError: imap_sort(): Argument #3 ($reverse) must be of type bool, int given
```
https://github.com/barbushin/php-imap/issues/563#issuecomment-867584500
> fix php 8.0 sort

- composer.json
- src/PhpImap/Imap.php
Quick & dirty.
But since https://php.watch/versions/8.1/IMAPConnection-resource says:
> All functions that previously accepted resources accept the new type as well. 
This might indeed be all that's needed - at least it works for me ;-)
Closes https://github.com/barbushin/php-imap/issues/624
> Hacking PHP 8.1 compatibility

- phpunit.xml
Fixes the following deprecation warning:
```shell
/home/runner/work/php-imap/php-imap/vendor/bin/phpunit --testdox --stop-on-failure --coverage-clover=clover.xml
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.0.13 with Xdebug 3.1.1
Configuration: /home/runner/work/php-imap/php-imap/phpunit.xml
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```
> Fix deprecated coverage XML config

- tests/unit/Fixtures/IncomingMailAttachment.php
- tests/unit/Issue519Test.php
This fixes the following PHP unit error:
```shell
Issue519 (PhpImap\Issue519)
✘  with data set "inline" [0.56 ms]
│
│ Failed asserting that actual size 1 matches expected size 0.
│
│ /home/runner/work/php-imap/php-imap/tests/unit/Issue519Test.php:177
│
```
This was caused and is related to the pull request #623.
> Fix Issue 519 PHP unit test

- composer.json
Relates to PR #639 and can not be fixed at the moment as it's a false-positive.
Needs to be re-added in the future, but for now it gets removed, so that the pipeline is helpful again.
> Remove composer require checker to fix pipeline

- .github/workflows/php.yml
- composer.json
To avoid updating all the time the Github workflow config, this change should dynamically load and test the respective PHP versions, which are supported / defined by the `composer.json`.
Avoids pull requests like #642 in the future.
> Dynamically test PHP versions depending on composer.json

- README.md
- composer.json
- examples/get_and_parse_unseen_emails.php
- src/PhpImap/Exceptions/ConnectionException.php
- src/PhpImap/Imap.php
- tests/unit/ImapTest.php
This change solves the issue, that the original IMAP connect error gets masked.
`ConnectionException::getErrors($select = 'first')` is a new function, which allows to get either all IMAP errors, only the first or last reported error.
`ConnectionException::getMessage()` is still simply returning a string. This string contains now all IMAP errors as JSON encoded format. The implementation allows further options for the future, if necessary.
Example code to test:
```php
<?php
require_once __DIR__.'/../vendor/autoload.php';
use PhpImap\Exceptions\ConnectionException;
use PhpImap\Mailbox;
$mailbox = new Mailbox(
'{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
'some@gmail.com', // Username for the before configured mailbox
'wrongPassword', // Password for the before …
```
> #571: Improve ConnectionException handling

- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
This change adds all available email flags as property:
- `Seen` (email property `isSeen`)
- `Answered` (email property `isAnswered`)
- `Recent` (email property `isRecent`)
- `Flagged` (email property `isFlagged`)
- `Deleted` (email property `isDeleted`)
- `Draft` (email property `isDraft`)
Those can be accessed like this:
```php
<?php
require_once __DIR__.'/../vendor/autoload.php';
use PhpImap\Exceptions\ConnectionException;
use PhpImap\Mailbox;
$mailbox = new Mailbox(
'{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
'some@gmail.com', // Username for the before configured mailbox
'*********', // Password for the before configured username
__DIR__, // Directory, where attachments will be saved (optional)
'US-ASCII' // Server encoding (optional)
);
try {
$mail_ids = …
```
> #529: Add email flags as properties

- src/PhpImap/DataPartInfo.php
This change implements the suggestion from @yrccondor, which avoids downloading the attachments multiple times, when it's already downloaded. This improves the performance by saving time and reduces the required/used hardware resources.
Code to test it:
```php
<?php
require_once __DIR__.'/../vendor/autoload.php';
use PhpImap\Exceptions\ConnectionException;
use PhpImap\Mailbox;
$mailbox = new Mailbox(
'{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
'some@gmail.com', // Username for the before configured mailbox
'*********', // Password for the before configured username
__DIR__.'/files/', // Directory, where attachments will be saved (optional)
'US-ASCII' // Server encoding (optional)
);
try {
$mail_ids = $mailbox->searchMailbox('ALL');
} catch (ConnectionException …
```
> #585: Avoid fetching attachments when they are already downloaded

- src/PhpImap/Imap.php
- src/PhpImap/Mailbox.php
IMAP stream can be an IMAP resource or IMAP\Connection object. See https://www.php.net/manual/en/migration81.incompatible.php for further information.
Looks like as this has been forgotten when adding PHP 8.1 support in the past.
Solves #655.
---
Tested with different PHP major versions and the identical code: All versions were able to get the same emails incl. attachments and it always took around 10 seconds for 25 emails.
```shell
$ /c/PHP/7.3.12-nts/php.exe testing.php
Trying to connect to '{outlook.office365.com:993/imap/ssl}INBOX'...
Found 25 email(s)...
Total attachments: 26
time for getting mail Is: 9.846657037735 sec.
```
```shell
$ /c/PHP/7.4.26-nts/php.exe testing.php
Trying to connect to '{outlook.office365.com:993/imap/ssl}INBOX'...
Found 25 email(s)...
Total attachments: 26 …
```
> #655: Add missing PHP 8.1 support

- src/PhpImap/Imap.php
**Environment (please complete the following information):**
- PHP IMAP version: 7.4.27
- PHP Version: 7.4.27
- Type of execution: CLI
**Describe the bug**
The $reverse variable type conversion from boolean to integer has been removed in this [commit](https://github.com/barbushin/php-imap/commit/2cd5d0bcf4500f4cc70559a103d65a72b512700b), but imap_open() before PHP version 8 only accepts integer type. Thus, in PHP 7 this code ends with the error:
```
imap_sort() expects parameter 3 to be int, bool given at /var/www/virtual/site/htdocs/vendor/php-imap/php-imap/src/PhpImap/Imap.php:934
```
Also i found strange assignment in \PhpImap\Imap::sort():
```
/** @var int */
$criteria = $criteria;
```
I've added PHP version detection and removed legacy code.
Please review it.
Thank you!
> BUG: An argument $reverse of method \PhpImap\Imap::sort() has type boolean from PHP version 8 only

- .github/workflows/php_code_coverage.yml
- .github/workflows/php_static_analysis.yml
- .github/workflows/php_unit_tests.yml
- README.md
- composer.json
See https://www.php.net/supported-versions.php:
Resolves #593.
> Drop support for EoL PHP versions

- src/PhpImap/Mailbox.php
Hello,
This assumes that `\imap_ping` throwing `ValueError: IMAP\Connection is already closed` implies that there's no valid stream, and the library won't try to disconnect an already closed connection. This way the consumer doesn't have to handle this error.
See #680.
> Temporary fix for `IMAP\Connection is already closed` #680
