- src/ImapMailbox.php
allow Cyrillic characters in attachments
> fixed replace condition for attachments

- example/index.php
> dirname(__FILE__) replaced with __DIR__ in example

- src/PhpImap/IncomingMail.php
- src/PhpImap/Mailbox.php
There's important header Message-ID.
Please consider adding it into IncomingMail.
> Added IncomingMail::$messageId property

- src/PhpImap/Mailbox.php
> make expunge on disconnect optional

- composer.json
> Updated to use PSR-4

- src/PhpImap/Mailbox.php
> Decode partStructure parameters

- src/PhpImap/Mailbox.php
Add ability to fetch e-mail in MBOX format
Expose imapPath outside
Allow for custom mailbox creation
Get Mailboxes data
> Add functions to Mailbox

- src/PhpImap/Mailbox.php
Hi,
this is returning the values of [imap_headers().](http://php.net/manual/en/function.imap-headers.php)
> adding getMailboxHeaders() method

- composer.json
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no    |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |
> Add `extra.branch-alias` config at `composer.json` in order to allow installs from dev versions while respecting SemVer

- src/PhpImap/Mailbox.php
Adds the possibility to combine sort and search criterias
Example : $mailbox->sortMails(SORTARRIVAL, true, 'UNSEEN');
> Add search criteria to sortMails method

- README.md
As per issue [badges/shields#3238](/badges/shields/issues/3238)
> Fix downloads badge invalid response data

- .github/CONTRIBUTING/contributing.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other-issue.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Some issue, pull request and contributing templates were added.
> Merged master into develop

- src/PhpImap/DataPartInfo.php
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- Updated formatting of class DataPartInfo to make it more human-readable
- Issue #310: Fixed issue with unparseable datetimes and updated/added PHPUnit tests
> Improved function to parse datetimes

- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- Issue #313: Fixed skipping of args, when they are identical to their defaults
- Issue #314: Added support for parsing drafts
- Issue #277: Added PHPUnit tests to test functionality of decoding MIME strings
- Issue #253: Added charset property to IncomingMailAttachment
> Some small fixes and improvements

- .codeclimate.yml
- .travis.yml
- phpunit.xml
- src/PhpImap/DataPartInfo.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- Added CodeClimate for coverage
- Issue #321: Fixed PHP notice conversion failed / not allowed and priorized mbstring before iconv
- Issue #321: Fixed saving of attachments (did not not work anymore)
> Added CodeClimate and fixed some issues

- src/PhpImap/Mailbox.php
This also includes a bugfix for the `$head` variable causing my app to crash.
> Fix many typos

- .gitignore
- .php_cs.dist
- .travis.yml
- src/PhpImap/DataPartInfo.php
- src/PhpImap/Exceptions/ConnectionException.php
- src/PhpImap/Exceptions/InvalidParameterException.php
- src/PhpImap/IncomingMail.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
- tests/unit/RequirementsTest.php
Ready for review @Sebi94nbg 
If the tests don't pass, I'll tweak the rules.
The Symfony ruleset includes PSRs plus some rules I feel are relevant for any project (see documentation).
> Add php-cs-fixer

- src/PhpImap/Mailbox.php
> Possible fix issue #377

- .travis.yml
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
- Fixed issues reported by Travis CI
> Travis CI fixes

- .travis.yml
- README.md
- composer.json
- src/PhpImap/Mailbox.php
- Added PHP 7.4 support
- #404: Added additional checks to avoid undefined property issues
> Added PHP 7.4 support and additional checks

- composer.json
having packages auto-sorted makes git merges a little bit cleaner.
> composer config sort packages

- .php_cs.dist
- README.md
- examples/get_and_parse_all_emails_with_matching_subject.php
- examples/get_and_parse_all_emails_without_saving_attachments.php
- examples/get_and_parse_unseen_emails.php
- examples/get_and_parse_unseen_emails_save_attachments_one_by_one.php
making this a separate PR as it keeps coming up when tinkering in offline branches.
> modify trailing whitespace

- .travis.yml
- composer.json
* switched from `curl` + `chmod` to `composer require --dev`
* removed phpcs from composer.json, as it didn't appear to be referenced in the build.
> obtain php-cs-fixer via composer

- .gitignore
- .travis.yml
noticed that test coverage wasn't getting uploaded to code climate
> generate & upload coverage to code climate

- .php_cs.dist
- examples/get_and_parse_all_emails_with_matching_subject.php
- examples/get_and_parse_all_emails_without_saving_attachments.php
- examples/get_and_parse_unseen_emails.php
- examples/get_and_parse_unseen_emails_save_attachments_one_by_one.php
> run php-cs-fixer on examples

- .travis.yml
- composer.json
ensures code doesn't make it into the repo without appropriate dependencies.
> adding maglnet/composer-require-checker

- .editorconfig
correcting my error in previous PR
> correcting typo

- composer.json
additional merge correction issue (I likely should've manually rerun this on one of the rebases)
> correcting package order in require-dev

- src/PhpImap/Mailbox.php
> validate imap_mime_header_decode return value in decodeMimeStr method

- psalm.baseline.xml
- src/PhpImap/Mailbox.php
- tests/unit/MailboxTest.php
> yet more static analysis

- .travis.yml
- composer.json
- psalm.baseline.xml
- src/PhpImap/IncomingMail.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
- tests/unit/LiveMailboxTest.php
- tests/unit/MailboxTest.php
- tests/unit/RequirementsTest.php
typehint being absent causes php 7.2 build to fail
> typehint tinkering

- composer.json
- psalm.baseline.xml
- src/PhpImap/DataPartInfo.php
- src/PhpImap/IncomingMail.php
- tests/unit/Fixtures/DataPartInfo.php
- tests/unit/IncomingMailTest.php
- tests/unit/MailboxTest.php
- tests/unit/RequirementsTest.php
bumping up test coverage a little.
> incoming mail tests, refactoring mailbox tests re: methods deprecated in future version of phpunit

- psalm.baseline.xml
- src/PhpImap/Mailbox.php
* refactors method underlying Mailbox::searchMailboxFrom()
* implemented re: barbushin/php-imap#455
> adding general-purpose merging search method

- psalm.baseline.xml
forgot to update the baseline on the #460 pr
> updating baseline

- src/PhpImap/Imap.php
incorrect function names were copy-pasted in when fleshing out
implementation.
> correcting function names

- src/PhpImap/Imap.php
#469 didn't apply php-cs-fixer when I picked it into `develop`.
> satisfy php-cs-fixer

- .travis.yml
- psalm.baseline.xml
psalm/phpunit-psalm-plugin#52 has been merged, but a tagged release has not been made featuring the changes at the time of writing.
> phpunit 9 not supported by psalm/plugin-phpunit

- composer.json
- psalm.baseline.xml
- src/PhpImap/Imap.php
- src/PhpImap/Mailbox.php
need to make some tweaks separate from the #519 bugfix.
> satisfying static analysis

- README.md
> amend documentation re: 3.x changes

- src/PhpImap/DataPartInfo.php
- src/PhpImap/Mailbox.php
Reverts barbushin/php-imap#551
> Revert "Fix for #525 How to detect textPlain encoding"

- composer.json
- psalm.baseline.xml
- src/PhpImap/Imap.php
- tests/unit/AbstractLiveMailboxTest.php
- tests/unit/ImapTest.php
- tests/unit/LiveMailboxTestingTrait.php
* draft pending #534 
* fixes #526
> empty array is falsey and triggers exception

- src/PhpImap/DataPartInfo.php
- src/PhpImap/Mailbox.php
See https://github.com/barbushin/php-imap/issues/543#issuecomment-709519495.
> 543: Fix incorrect MIME decoding

- src/PhpImap/Mailbox.php
> Respect ServerEncoding for attachment Filenames

- src/PhpImap/Imap.php
This is a proposal to fix TypeError as i reported in #602
I've added a is_string check to avoid a TypeError
> Proposed fix for #602 (TypeError due to strict types)

- .php_cs.dist
- examples/get_and_parse_all_emails_with_matching_subject.php
- examples/get_and_parse_all_emails_without_saving_attachments.php
- examples/get_and_parse_unseen_emails.php
- examples/get_and_parse_unseen_emails_save_attachments_one_by_one.php
- src/PhpImap/DataPartInfo.php
- src/PhpImap/IncomingMailAttachment.php
- src/PhpImap/Mailbox.php
Closes #594
This PR updated the usage of deprecated methods for php cs. It also fixes some styling issues.
> Fix deprecated methods

- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
> Add X-Original-To header property

- src/PhpImap/IncomingMailHeader.php
- src/PhpImap/Mailbox.php
> #582: Make Cc-list equivalent to To-list

- README.md
- src/PhpImap/Mailbox.php
> 603: Add support for IMAP paths with leading/ending whitespaces

- .github/workflows/php.yml
> Update list of tested PHP versions

- .github/workflows/php_code_coverage.yml
- .github/workflows/php_static_analysis.yml
- .github/workflows/php_unit_tests.yml
- README.md
See documentation for further information: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
> Fix workflow pipeline

- src/PhpImap/DataPartInfo.php
- tests/unit/Fixtures/DataPartInfo.php
- tests/unit/LiveMailboxStringDecodingConvertingTest.php
> Issue #657: Fix encoding issues
